- name: Run home directory setup.
  command: /home/dgreid/HomeDir/setup.sh
  args:
      chdir: /home/dgreid/HomeDir
  become: yes
  become_user: dgreid
  ignore_errors: yes

- name: Install rust compilers
  shell: curl https://sh.rustup.rs -sSf | bash -s -- -y
  become: yes
  become_user: dgreid

- name: Install rust rls deps
  command: rustup component add rls rust-analysis rust-src
  become: yes
  become_user: dgreid

- name: crosvm git set push github
  command: git remote set-url --push github git@github.com:dgreid/crosvm.git
  args:
      chdir: /home/dgreid/crosvm

- name: crosvm add cros
  command: git remote add cros https://chromium.googlesource.com/chromiumos/platform/adhd
  args:
      chdir: /home/dgreid/crosvm
  ignore_errors: yes

- name: adhd git set push github
  command: git remote set-url --push github git@github.com:dgreid/adhd.git
  args:
      chdir: /home/dgreid/adhd

- name: adhd add cros
  command: git remote add cros https://chromium.googlesource.com/chromiumos/third_party/adhd
  args:
      chdir: /home/dgreid/adhd
  ignore_errors: yes

- name: build minijail
  command: make -j4
  args:
      chdir: /home/dgreid/minijail

- name: install minijail
  command: cp *.so /lib64
  args:
      chdir: /home/dgreid/minijail

- name: dgreid is owner
  command: chown -R dgreid *.*
  args:
      chdir: /home/dgreid
