- name: Install packages
  apt: name={{item}}
  with_items:
    - autoconf
    - automake
    - bc
    - binutils-common
    - bison
    - build-essential
    - bzip2
    - clang
    - clangd
    - curl
    - device-tree-compiler
    - flex
    - gdb
    - git
    - git-email
    - git-man
    - gnupg
    - libcap-ng-dev
    - libdbus-1-dev
    - libfdt-dev
    - libffi-dev
    - libprotobuf-c-dev
    - libprotobuf-dev
    - lynx
    - neomutt
    - net-tools
    - ninja-build
    - openssh-client
    - openssh-server
    - openvpn
    - pass
    - protobuf-compiler
    - python3
    - tig
    - tmux
