#cloud-config

package_update: true
package_upgrade: true

users:
  - name: dgreid
    gecos: Dylan Reid
    groups: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBMu/0O6PtVg+8SAynHa2h4GG/XwOpX9ZASIjZIsS+Gg dylanreid@dylans-MacBook-Pro.local
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFdDfad42zuPcvV6Irk21LIoS8KohF2XTYTRP0QQIRku dgreid@Dylans-MacBook-Air.local
    plain_text_passwd: 'test0000'


packages:
  - ansible
  - autoconf
  - automake
  - bc
  - binutils-common
  - bison
  - build-essential
  - bzip2
  - clang
  - clangd
  - curl
  - device-tree-compiler
  - flex
  - gdb
  - git
  - git-email
  - git-man
  - gnupg
  - libcap-ng-dev
  - libdbus-1-dev
  - libfdt-dev
  - libffi-dev
  - libprotobuf-c-dev
  - libprotobuf-dev
  - lynx
  - neomutt
  - net-tools
  - ninja-build
  - openssh-client
  - openssh-server
  - openvpn
  - pass
  - protobuf-compiler
  - python3
  - tig
  - tmux

ansible:
  pull:
    url: "https://github.com/dgreid/ansible-crostini.git"
    playbook-name: local.yml
